"""Значения ссылок для авторизации по регионам через госуслуги
https://help.dnevnik.ru/hc/ru/articles/224914888-%D0%90%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%B2-%D0%94%D0%BD%D0%B5%D0%B2%D0%BD%D0%B8%D0%BA-%D1%80%D1%83-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-%D0%BF%D0%BE%D1%80%D1%82%D0%B0%D0%BB-%D0%B3%D0%BE%D1%81%D1%83%D1%81%D0%BB%D1%83%D0%B3
"""

__BASE_URL = "https://{}.dnevnik.ru"


AMUR_REGION = __BASE_URL.format(28)
ARKHANGELSK_REGION = __BASE_URL.format(29)
ASTRAKHAN_REGION = __BASE_URL.format(30)
VORONEZH_REGION = __BASE_URL.format(36)
JEWISH_AUTONOMOUS_REGION = __BASE_URL.format(79)
IVANOVO_REGION = __BASE_URL.format(37)
IRKUTSK_REGION = __BASE_URL.format(38)
KIROV_REGION = __BASE_URL.format(43)
LENINGRAD_REGION = __BASE_URL.format(47)
NIZHNY_NOVGOROD_REGION = __BASE_URL.format(52)
NOVGOROD_REGION = __BASE_URL.format(53)
NOVOSIBIRSK_REGION = __BASE_URL.format(54)
OMSK_REGION = __BASE_URL.format(55)
ORENBURG_REGION = __BASE_URL.format(56)
ADYGEA_REPUBLIC = __BASE_URL.format("01")
BASHKORTOSTAN_REPUBLIC = __BASE_URL.format("02")
DAGESTAN_REPUBLIC = __BASE_URL.format("05")
CRIMEA_REPUBLIC = __BASE_URL.format(91)
KARELIA_REPUBLIC = __BASE_URL.format(10)
NORTH_OSSETIA_REPUBLIC = __BASE_URL.format(15)
ST_PETERSBURG = __BASE_URL.format(78)
SARATOV_REGION = __BASE_URL.format(64)
SVERDLOVSK_REGION = __BASE_URL.format(66)
SEVASTOPOL = __BASE_URL.format(92)
TAMBOV_REGION = __BASE_URL.format(68)
CHYKOTKA_AUTONOMOUS_OKRUG = __BASE_URL.format(87)
